[features]
seeds = false
skip-lint = false

[programs.localnet]
errors = "Afo1di5V5r1nnEWVRz8Js4u8KQuqjAbH4NUW2qWEkP2T"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
client = "yarn run ts-node client/*.ts"
